src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Enum\Priority;
use App\Enum\Status;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 10, enumType:Priority::class)]
    private Priority $priority = Priority::LOW;

    #[ORM\Column(length: 10 , enumType: Status::class)] 
    private Status $status = Status::DONE;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPriority(): Priority
    {
        return $this->priority;
    }

    public function setPriority(Priority $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getStatus(): Status
    {
        return $this->status;
    }

    public function setStatus(Status $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/TicketType.php
<?php

namespace App\Form;

use App\Entity\Ticket;
use App\Enum\Priority;
use App\Enum\Status;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TicketType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('priority', ChoiceType::class, [
                'choices' => Priority::cases(),
                'choice_label' => fn(Priority $p) =>$p->name,
                'choice_value' => fn(?Priority $p) =>$p?->value,
            ])
            ->add('status', ChoiceType::class, [
                'choices' => Status::cases(),
                'choice_label' => fn(Status $s) => $s->name,
                'choice_value' => fn(?Status $s) => $s?->value,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ticket::class,
        ]);
    }
}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Ticket;
use App\Form\TicketType;
use App\Repository\TicketRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/')]


final class TicketController extends AbstractController
{
    #[Route(name: 'app_ticket_index', methods: ['GET'])]
    public function index(TicketRepository $ticketRepository, EntityManagerInterface $em, UserPasswordHasherInterface $hasher): Response

    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('ticket/index.html.twig', [
            'tickets' => $ticketRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_ticket_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $ticket = new Ticket();
        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($ticket);
            $entityManager->flush();

            return $this->redirectToRoute('app_ticket_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ticket/new.html.twig', [
            'ticket' => $ticket,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ticket_show', methods: ['GET'])]
    public function show(Ticket $ticket): Response
    {
        return $this->render('ticket/show.html.twig', [
            'ticket' => $ticket,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ticket_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ticket $ticket, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_ticket_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ticket/edit.html.twig', [
            'ticket' => $ticket,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ticket_delete', methods: ['POST'])]
    public function delete(Request $request, Ticket $ticket, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($ticket);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_ticket_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ticket/_delete_form.html.twig
<form method="post" action="{{ path('app_ticket_delete', {'id': ticket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ticket/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ticket/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ticket{% endblock %}

{% block body %}
    <h1>Edit Ticket</h1>

    {{ include('ticket/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_ticket_index') }}">back to list</a>

    {{ include('ticket/_delete_form.html.twig') }}
{% endblock %}

templates/ticket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ticket index{% endblock %}

{% block body %}
    <h1>Ticket index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.id }}</td>
                <td>{{ ticket.title }}</td>
                <td>{{ ticket.description }}</td>
                <td>{{ ticket.priority.value }}</td>
                <td>{{ ticket.status.value }}</td>
                <td>{{ ticket.createdAt ? ticket.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_ticket_show', {'id': ticket.id}) }}">show</a>
                    <a href="{{ path('app_ticket_edit', {'id': ticket.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_ticket_new') }}">Create new</a>
{% endblock %}

templates/ticket/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ticket{% endblock %}

{% block body %}
    <h1>Nouveau Ticket</h1>

{{ form_start(form, {attr: {class: 'row g-3'}}) }}
    <div class="col-12">
        {{ form_row(form.title) }}
    </div>
    <div class="col-12">
        {{ form_row(form.description) }}
    </div>
    <div class="col-12">
        {{ form_row(form.priority) }}
    </div>
    <div class="col-12">
        {{ form_row(form.status) }}
    </div>
    <button type="submit" class="btn-form" arial-label="Bouton de validation">Je m'inscris</button>
    <a href="{{ path('app_ticket_index') }}">back to list</a>
{{ form_end(form) }}
{% endblock %}

templates/ticket/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ticket{% endblock %}

{% block body %}
    <h1>Ticket</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ticket.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ ticket.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ ticket.description }}</td>
            </tr>
            <tr>
                <th>Priority</th>
                <td>{{ ticket.priority.value }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ ticket.status.value }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ ticket.createdAt ? ticket.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_ticket_index') }}">back to list</a>

    <a href="{{ path('app_ticket_edit', {'id': ticket.id}) }}">edit</a>

    {{ include('ticket/_delete_form.html.twig') }}
{% endblock %}